[phases.setup]
nixPkgs = ["nodejs-20_x"]  # Correction du nom du package

[phases.install]
cmds = ["cd server && npm ci"]  # Supprime --only=production si tu veux aussi les devDependencies

[start]
cmd = "cd server && npm start"  # Utilise bien cmd au singulier